exclude:
- cSpell.json
- README.md
- fr
- nl
- env

defaults:
- scope:
    path: index.html
    type: pages
  values:
    layout: home
- scope:
    path: ""
    type: pages
  values:
    layout: page

collections:
- history
- units
- participants
- sponsors
- join_us

redirects:
  fr:
    label: Français
    base:
      TEST: https://test.pendragon.be/bw2021fb/fr
      PROD: http://fanionbleu2021.be
      development: http://localhost:4000
  nl:
    label: Nederlands
    base:
      TEST: https://test.pendragon.be/bw2021fb/nl
      PROD: http://blauwewimpel2021.be
      development: http://localhost:4000

# defaults for dev tests
language: fr
lcid: fr-FR
collections_dir: fr/cards
title: Fanion Bleu 2021
email_domain: '@fanionbleu2021.be'
email_aliases_map:
  enrol: info
  sponsors: info
  press: info
  volunteers: info
  it_support: it
