language: nl
collections_dir: nl/cards
title: Blauwe Wimpel 2021
email_domain: '@blauwewimpel2021.be'
email_aliases_map:
  enrol: info
  sponsors: info
  press: info
  volunteers: info
  it_support: it
