language: fr
lcid: fr-FR
collections_dir: fr/cards
title: Fanion Bleu 2021
email_domain: '@fanionbleu2021.be'
email_aliases_map:
  enrol: info
  sponsors: info
  press: info
  volunteers: info
  it_support: it
