name: Deploy test website on push

on:
  push:
    branches:
      - site/test

env:
  target: TEST

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf
      # This is version v2.3.2, using SHA-1 to avoid backdoor introduction
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
      # This is version 4.0.0, using SHA-1 to avoid backdoor introduction
      # This action is not verified by Github, hence we must authorize "all" actions!
      with:
        server: ${{ secrets.${target}_FTP_SERVER }}
        username: ${{ secrets.${target}_FTP_USER }}
        password: ${{ secrets.${target}_FTP_PASSWORD }}
        server-dir: ${{ secrets.${target}_FTP_TARGETDIR }}
        exclude:
          - .git*
          - .git*/**
          - cSpell.json
