name: Deploy test website on push

on:
  push:
    branches:
    - site/TEST

env:
  target: TEST

jobs:
  jekyll-build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [fr, nl]
    steps:

    - name: Get latest code
      uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf  # This is version v2.3.2, using SHA-1 to avoid backdoor introduction

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - name: Retrieving gems from cache
      uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a  # This is version v2.1.3, using SHA-1 to avoid backdoor introduction
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Making sure Jekyll container may write to required files and dirs
      run: |
        mkdir .jekyll-cache _site
        touch Gemfile.lock
        chmod a+w Gemfile.lock

    - name: Jekyll build
      uses: docker://jekyll/jekyll@sha256:de110e0fdde342de0cb6fd5c63f64934b6ce25d0dd826c67113b3a5a3370784e  # This is version 4.2.0, using SHA-256 to avoid backdoor introduction
      # uses: docker://jekyll/builder@sha256:b918b81939a1076dce89d142c0764c2c3cb93858f56ecf4f04ad0387338e77aa  # This is version 4.2.0, using SHA-256 to avoid backdoor introduction
      env:
        JEKYLL_ENV: TEST
      with:
        args: jekyll build --trace --verbose --config _config.yml,_config.${{ matrix.language }}.yml
    
    - name: Show build result
      run: |
        pwd
        ls -lhAF _site/

    - name: Preserving built files
      uses: actions/upload-artifact@v2
      with:
        name: web-site[TEST][${{ matrix.language }}]
        path: _site/

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: jekyll-build
    strategy:
      matrix:
        language: [fr, nl]
    steps:   

    - name: Retrieving built files
      uses: actions/download-artifact@v2
      with:
        name: web-site[TEST][${{ matrix.language }}]
        path: .

    - name: Show build result
      run: |
        pwd
        ls -lhAF

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01  # This is version 4.0.0, using SHA-1 to avoid backdoor introduction
        # This action is not verified by Github, hence we must authorize "all" actions!
      with:
        server: ${{ secrets.TEST_FTP_SERVER }}
        username: ${{ secrets.TEST_FTP_USER }}
        password: ${{ secrets.TEST_FTP_PASSWORD }}
        server-dir: ${{ secrets.TEST_FTP_TARGETDIR }}/${{ matrix.language }}/
